%YAML:1.0
---
Markers:
  - Points:
      -
        freq: 8000
        x: -0.015
        y: 0.015
        z: 0.0
      -
        freq: 8200
        x: 0.015
        y: 0.015
        z: 0.0
      -
        freq: 8400
        x: 0.015
        y: -0.015
        z: 0.0
      -
        freq: 8600
        x: -0.015
        y: -0.015
        z: 0.0
    ID: 1

  - Points:
      - freq: 10000
        x: -0.015
        y: 0.015
        z: 0.0
      - freq: 10200
        x: 0.015
        y: 0.015
        z: 0.0
      - freq: 10400
        x: 0.015
        y: -0.015
        z: 0.0
      - freq: 10600
        x: -0.015
        y: -0.015
        z: 0.0
    ID: 2

  - Points:
      - freq: 5000
        x: -0.015
        y: 0.015
        z: 0.0
      - freq: 5000
        x: 0.015
        y: 0.015
        z: 0.0
      - freq: 5000
        x: 0.015
        y: -0.015
        z: 0.0
      - freq: 5000
        x: -0.015
        y: -0.015
        z: 0.0
    ID: 3